### ISSUE TITLE
[Request] Сборка для Win7 x32

### ISSUE THREAD

**Issue by postmasta** [bol-van/zapret-win-bundle#11]
Большая просьба собрать билд под Win7 x32. [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) на Win7 x32 работает хорошо, но против самых последних блокировок ютуба на некоторых провайдерах он уже не помогает, нужны новые стратегии обхода.

**Comment by bol-van** [comment]
Это надо в исключительных случаях, а обновлять надо все время.
Пусть кто-то сторонний сделает.

**Comment by postmasta** [comment]
> а обновлять надо все время.

Обновлять не надо. Просто сделайте одну сборку, выложите на ntc.party, например, и этого будет достаточно.

> Пусть кто-то сторонний сделает.

Если за столько лет никто другой не сделал, то уже и не сделает.

**Comment by bol-van** [comment]
Если процессор поддерживает AMD64 инструкции, то давно уже пора переходить на x64.

**Comment by postmasta** [comment]
> Если процессор поддерживает AMD64 инструкции, то давно уже пора переходить на x64.

Дело не в проце, а в памяти. Старые слабые машинки с 1-2-3Гб нормально можно использовать для онлайн серфинга и кино. Ставить на них x64 ось не лучшая идея, в т.ч. из-за дров на них и подключенную периферию, и памяти добавить тоже часто просто нет возможности.

**Comment by bol-van** [comment]
https://github.com/bol-van/zapret-win32

**Comment by postmasta** [comment]
> https://github.com/bol-van/zapret-win32

Большое спасибо, всё работает!

**Comment by TYMA22389** [comment]
> https://github.com/bol-van/zapret-win32

перезалейте пожалуйста

**Comment by bol-van** [comment]
Бинарики в релизах в основной репе. Там и win32 тоже есть.
А bundle и не было никогда готового
