### ISSUE TITLE
Добавить предупреждение о антивирусе в README

### ISSUE THREAD

**Issue by vadimk1337** [bol-van/zapret-win-bundle#14]
Люди не читают quick_start_windows.txt из zapret-master, а сразу идут сюда, а потом [жалуются ](https://github.com/bol-van/zapret/discussions/503)на вирусы. На самом деле zapret-win-bundle нельзя скачать в zip формате потому что windows defender жалуется на вирус. Поэтому надо добавить это предупреждение из quick_start_windows в README этого репозитория , так у людей отпадут вопросы. 

Antiviruses may react poorly to Windivert.
Cygwin has a significant list of incompatibilities with antivirus software. Many antiviruses break it.
https://www.cygwin.com/faq.html#faq.using.bloda
If this is the case, use exceptions. If that doesn't help, disable the antivirus entirely.

Антивирусы могут плохо реагировать на windivert.
cygwin имеет внушительный список несовместимостей с антивирусами. Многие антивирусы его ломают.
https://www.cygwin.com/faq.html#faq.using.bloda
Если это имеет место , используйте исключения. Если это не помогает - отключайте антивирус совсем.

**Comment by bol-van** [comment]
Добавлено
