### ISSUE TITLE
Описание файлов 

### ISSUE THREAD

**Issue by Allen-Wa1ker** [bol-van/zapret-win-bundle#15]
Здравствуйте. Хотел предложить добавить описание каждого запускаемого файла, это поможет, даже неопытным пользователям, понять как работает инструмент. И для таких пользователей можно добавить инструкцию по удалению инструмента.
P.S. Серьёзно, я встречал не одного человека, который спрашивал меня, как пользоваться этим инструментом. И понимая это, я решил, что будет лучше, если эта информация будет в инструкции.

**Comment by bol-van** [comment]
Не очень понял что имеется в виду

**Comment by vadimk1337** [comment]
Допустим killall.exe, что это?  
Или же reload_lists.cmd?
Типа сделать док с кратким описанием что делают файлы в zapret-winws, потому что уже файлов много и уже более запуталось всё.

**Comment by Allen-Wa1ker** [comment]
> Не очень понял что имеется в виду

Как написал vadimk1337, что то подобное. Так будет проще разобраться с назначением файлов.

**Comment by bol-van** [comment]
На dll и sys не стоит обращать внимание. Отметаем.
cmd несут в себе внятное название для чего это. подробности в docs/windows.txt
*txt содержат листы. название само за себя говорит, и можно посмотреть редактором текстовый файл
killall имеет единственное назначение. это именно то, что есть на linux. послать сигнал процессу.
HUP заставляет перечитать winws листы и ипсеты. Чтобы не перезапускать процесс.
reload_lists.cmd запускает kilalll -HUP winws

winws основан на cygwin. изначально это *nix прога

**Comment by Allen-Wa1ker** [comment]
> На dll и sys не стоит обращать внимание. Отметаем. cmd несут в себе внятное название для чего это. подробности в docs/windows.txt *txt содержат листы. название само за себя говорит, и можно посмотреть редактором текстовый файл bin содержат кастомные пейлоады для дурения. они задействованы в пресете. killall имеет единственное назначение. это именно то, что есть на linux. послать сигнал процессу. HUP заставляет перечитать winws листы и ипсеты. Чтобы не перезапускать процесс. reload_lists.cmd запускает killall -HUP winws
> 
> winws основан на cygwin. изначально это *nix прога

По поводу DLL, sys, txt - они особенно не запутывают и у, большинства, людей не возникают вопросы по ним. Но вот часто возникают вопросы: зачем тот или иной .CMD файл? что он делает? нужно ли его запускать? как удалить инструмент а случае необходимости?

У меня лично спрашивали про task, service, killall и про удаление. Потому и предложил краткое описание каждого cmd добавить в инструкцию по использованию.

**Comment by Allen-Wa1ker** [comment]
> Удалять так, как устанавливал. Если жмякал все подряд, то 2 батника del надо запускать и закрывать окно. Инструкция для windows - отдельная. Это уточняющий текст, описывающий особенности windows версии. Для знакомых с zapret-ом вообще.
> 
> Если чел пришел и хочет тыкнуть на авось - для него есть preset_russia. В режиме "попробовать". Хорошо - окей, нет - удалил и забыл, пошел искать VPN
> 
> Что вы предлагаете и где написать ?

Вот эти слова добавить в reedme.txt(в версию zepret-win-bundle), чтобы не опытные пользователи не жали туда-сюда, а если и нажали - знали как все исправить.

**Comment by bol-van** [comment]
Причесал немного
