### ISSUE TITLE
Сделать autohostlist.txt действительно auto

### ISSUE THREAD

**Issue by vadimk1337** [bol-van/zapret-win-bundle#16]
Просто надо взять у goodbyedpi скрипт 0_russia_update_blacklist_file.cmd переименовать в update_autohostlist.bat 
и в скрипте заменить russia-blacklist.txt на autohostlist.txt, всё, теперь в zapret-win-bundle\zapret-winws будет скрипт который сайты берёт, тогда будет паритет в функционале с goodbyedpi.

**Comment by bol-van** [comment]
У вас все смешалось в кашу.
Автолист в понятиях zapret - это лист, который ведется самим zapret на основании анализа ответов от сервера.
Почитайте об этом в readme.

Ваш вариант - это обычный обновляемый лист, который можно и самому прикрутить несложно.
В linux и openwrt версии есть целая система подкачки таких листов. В винде - не сделано

**Comment by alk2git** [comment]
для windows обновитель russia-blacklist можно взять из комплекта GoodbyeDPI - 0_russia_update_blacklist_file.cmd

**Comment by vadimk1337** [comment]
Ну ок. 
Тогда поменяйте описание

preset_russia.cmd, preset_russia_autohostlist.cmd : интерактивный запуск наиболее распространенной стратегии для России

на

preset_russia.cmd : интерактивный запуск наиболее распространенной стратегии для России
preset_russia_autohostlist.cmd: интерактивный запуск наиболее распространенной стратегии для России с автоматическим заполнением autohostlist.txt на основе обнаружении блокировки

Так будет понятно что за autohostlist и можно закрыть ишью

**Comment by bol-van** [comment]
ok, изменено
