### ISSUE TITLE
Улучшить блокчек

### ISSUE THREAD

**Issue by vadimk1337** [bol-van/zapret-win-bundle#18]
У меня для quick параметр который я просто нашёл в дисскусиях и он рабочий --filter-udp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake --dpi-desync-repeats=5 --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^

Но блокчек просто сделает так:
 rr4---sn-jvhnu5g-c35d.googlevideo.com

- checking winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake --dpi-desync-repeats=5
curl: (28) Connection timed out after 2015 milliseconds
UNAVAILABLE code=28

Всёдело в том что он не проверяет  --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin"
А без него работать не будет.  Надо чтобы это интегрировать в сам блокчек чтобы он ещё и проверял из папки zapret\files\fake

Он бы после check http3 QUIC (default : Y) (Y/N) ? y
Запрашивал ещё и fake, надо было бы написать quic_initial_www_google_com он бы брал из папки zapret-win-bundle\blockcheck\zapret\files\fake

и потом бы спрашивал искать только с fake или fake+без fake.
Это уже не специфичный случай,  это уже база. Потому что блокчек без фейков уже не вывозит.

**Comment by bol-van** [comment]
Это частные случае, которые загромождают прогу.
Их может быть в будущем великое множество.
Делать комбайн из частных случаев точно не стану.
Чтобы решить этот вопрос специально созданы переменные PKTWS_EXTRA

> 
> В blockcheck внесена поддержка переменных
> TPWS_EXTRA - для tpws
> PKTWS_EXTRA - для nfqws/dvtws/winws
> эти переменные добавляются к параметрам тестовых запусков соотв демонов
> 
> основное применение - включение разных внешних пейлоадов
> 
> PKTWS_EXTRA="--dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" ./blockcheck.sh
> 
> чтобы не уродовать код скрипта ради сиюминутных частных веяний и хотелок
