### ISSUE TITLE
Провайдер подменяет dns

### ISSUE THREAD

**Issue by 1vanK** [bol-van/zapret-win-bundle#20]
А как-то можно в проверялку добавить поддержку cloudflare? А то в браузере уже встроенный dns через https есть, что-то дополнительно ставить не охота

**Comment by bol-van** [comment]
Проверялка использует системный DNS.
Заменить его ваша задача, а не проверялки.
Побочный функционал интегрироваться не будет, чтобы не замусоривать и утяжелять код

**Comment by 1vanK** [comment]
Ну у меня десяточка, системный dns через https я так понял можно врубить только в 11
https://winitpro.ru/index.php/2020/07/10/nastroyka-dns-over-https-doh-v-windows/

**Comment by bol-van** [comment]
Там есть хак на последнем билде винды. Всегда можно навесить свой DNS.
curl, конечно, поддерживает doh. Но с ним есть большая проблема. Время запроса.
А его curl будет делать каждый раз. Каждая проверка + почти секунда.
Конечно, вопрос решить можно, подтянув какую-то отдельную утилиту для doh запросов, чтобы сделать запрос единожды. Но стоит ли это выделки ? Практически этим можно пользоваться только в готовом варианте на винде в bundle. Тк стандартной утилиты в *nix системах обычно нет

**Comment by miaomiaosoft** [comment]
[AdGuard Home](https://github.com/AdguardTeam/AdGuardHome)

**Comment by wiking46** [comment]
Для Windows 10 и Arch использую control d с uncensored, можно также использовать control d с comss dns, дополнительно этот uncensored прописан в doh браузеров для поддержки ech.

**Comment by bol-van** [comment]
В последней версии сделан автоматический переход на DoH в блокчеке, если обнаружена подмена

**Comment by 1vanK** [comment]
Класс, спасибо!
