### ISSUE TITLE
Как удалить?

### ISSUE THREAD

**Issue by Pajojda1986** [bol-van/zapret-win-bundle#24]
Не понимаю как удалить, жалуется на открытые процессы, через диспечер невозможно их закрыть

**Comment by bol-van** [comment]
Сегодня закоммитил windivert_delete.cmd
Сначала убить все winws, потом запустить этот батник

**Comment by IVladeg** [comment]
> Сегодня закоммитил windivert_delete.cmd Сначала убить все winws, потом запустить этот батник

Подскажите, пожалуйста, а как убить все winws?
blockcheck пишет мне:
!!! WARNING. some dpi bypass processes already running !!!
!!! WARNING. blockcheck requires all DPI bypass methods disabled !!!
!!! WARNING. pls stop all dpi bypass instances that may interfere with blockcheck !!!

я из папки zapret-winws пытаюсь запускать файлы:
task_stop, task_remove
service_stop, service_del

потом заново запускаю blockcheck, но он продолжает писать что dpi работает? 
А как убить то убить все winws?

**Comment by bol-van** [comment]
Вопрос из школы комп грамотности "как убить процесс"
Учиться пользоваться диспетчером задач

**Comment by 7918514** [comment]
> А как убить то убить все winws?

Через CMD от имени Администратора
taskkill /F /IM winws.exe

**Comment by mrak2085** [comment]
Windivert64.sys удали при помощи autoruns т.к. это майнер, но я человек хороший я создателю на покушать оставлю
