### ISSUE TITLE
Замените vbs скрипты на powershell

### ISSUE THREAD

**Issue by kirill8618** [bol-van/zapret-win-bundle#28]
Замените vbs скрипты на powershell, в последних версиях windows отсутствует обработчик .vbs и не все хотят его устанавливать

**Comment by bol-van** [comment]
В последних это в каких ?
powershell - дикий тормоз подобно java, тк написан на .NET

**Comment by bol-van** [comment]
Вижу, с 24H2 он того.  ОК, напишем на C прогу, благо только для bundle надо

**Comment by bol-van** [comment]
Сделано. Можно проверять
