### ISSUE TITLE
The driver file is signed with a digital certificate from a Chinese company

### ISSUE THREAD

**Issue by miaomiaosoft** [bol-van/zapret-win-bundle#3]
When I looked at the digital certificate for WinDivert64.sys I found a digital signature from a Chinese company

“成都密思听科技有限公司”
“Chengdu Mishearing Technology Co.”

I don't know if this has any effect on system security？

**Comment by bol-van** [comment]
windivert files are taken from the author's site
https://reqrypt.org/download
compare them if you like or take other version
versions <2.2.0 are not tested and can fail

**Comment by miaomiaosoft** [comment]
Okay, thank you very much for your answer.
