### ISSUE TITLE
Добавить поддержку windows 10

### ISSUE THREAD

**Issue by ReginaLain** [bol-van/zapret-win-bundle#30]
Очень не хватает поддержки ARM64 десятки.
![Untitled](https://github.com/user-attachments/assets/51512ee9-8379-4a24-ae4e-55474c9864b1)

**Comment by bol-van** [comment]
Там тоже можно завести, но потребуется вариант win32 с заменой SYS на arm версию. Ее можно взять из bundle.
win32 версию из основной репы.
Полноценный bundle для 32 делать нет в планах. очень мало кому нужно

**Comment by Verity-Freedom** [comment]
> Там тоже можно завести, но потребуется вариант win32 с заменой SYS на arm версию. Ее можно взять из bundle. win32 версию из основной репы. Полноценный bundle для 32 делать нет в планах. очень мало кому нужно Режим testsigning тоже придется включить. bcdedit команда есть в батнике для arm64 win11

К сведению, Zapret на Win 7 x64 тоже работает только после bcdedit. Проблема включая меня была много у кого. На десятке без bcdedit заводится.

**Comment by bol-van** [comment]
читаем docs/windows.md

**Comment by bol-van** [comment]
Сделано упрощенное 1-кнопочное лекарство для win7.
