### ISSUE TITLE
Zapret работал, но теперь ничего не грузит

### ISSUE THREAD

**Issue by miranig** [bol-van/zapret-win-bundle#31]
Пожалуйста, объясните простым языком. Установила запрет, все работало прекрасно, пока не решили сменить роутер. После настройки роутера с запретом начались проблемы. Ничего не грузит, как не старалась бы. Что можно сделать в этом случае? Помогите, пожалуйста!
![image](https://github.com/user-attachments/assets/cff16005-81f8-4b7c-9a6b-73475a1e6b2d)

**Comment by bol-van** [comment]
А причем тут win bundle ? Это надо в дискуссии идти в основную репу
Под issue это тоже никак не катит
