### ISSUE TITLE
Находит вирус в virustotal + (-48) community score

### ISSUE THREAD

**Issue by dsijdshaij** [bol-van/zapret-win-bundle#36]
![изображение](https://github.com/user-attachments/assets/e78f36e5-4d32-410a-b8b5-3bb6a7529ead)

**Comment by bol-van** [comment]
Это не вирус, а шиза антивируса

**Comment by dsijdshaij** [comment]
> Это не вирус, а шиза антивируса

Скинь исходник

**Comment by bol-van** [comment]
https://github.com/basil00/WinDivert

а так же см цифровую подпись драйвера

**Comment by bol-van** [comment]
2 из 72 это большинство ?
