### ISSUE TITLE
Не понимаю, почему не работает

### ISSUE THREAD

**Issue by ViLiDi230** [bol-van/zapret-win-bundle#39]
Есть две стратегии: в одной hostlist-auto указан как список, в другом hostlist:
И проблема в том, что там где hostlist-auto сайты открываются верно, а там где просто hostlist они не открываются
Файл в обоих случаях считывается
Для примера две стратегии:
--wf-l3=ipv4 --wf-tcp=443 --hostlist-auto="%~dp0hosts.txt" --dpi-desync=syndata,split2 --wssize 1:6 ^
--wf-l3=ipv4 --wf-tcp=443 --hostlist="%~dp0hosts.txt" --dpi-desync=syndata,split2 --wssize 1:6 ^
В файле находится только один домен: soundcloud.com
При попытке зайти на сайт в первой стратегии все проходит гладко, во второй происходит ошибка 
В первом случае:
![image](https://github.com/user-attachments/assets/c2953220-48b3-4431-8fbd-0ff57daff8c7)
Во втором случае: 
![image](https://github.com/user-attachments/assets/9dfcfc28-4184-4f72-a209-1a3b407ad8af)
Может я что-то не так указываю?

**Comment by bol-van** [comment]
wssize является дурилкой нулевой фазы, на которую не действует хостлист
Профили с --hostlist* и без --hostlist-auto никогда не применят wssize, а hostlist-auto применит, тк является приоритетным. Все это в доке описано

**Comment by ViLiDi230** [comment]
> wssize является дурилкой нулевой фазы, на которую не действует хостлист Профили с --hostlist* и без --hostlist-auto никогда не применят wssize, а hostlist-auto применит, тк является приоритетным. Все это в доке описано

О как, оказывается проглядел про эту особенность dpi-desync. Большое спасибо
