### ISSUE TITLE
Поиск сети DOTA 2 после всех проделанных шагов

### ISSUE THREAD

**Issue by mihailvityaev** [bol-van/zapret-win-bundle#4]
Как теперь удалить все то, что я сделал???

**Comment by mihailvityaev** [comment]
Ютуб тоже перестал работать

**Comment by mihailvityaev** [comment]
Помогло решение:

Закрыть окно с замком и заголовком zapret
Удалить службы. Есть батник service_del.cmd. От имени админа
Удалить scheduled tasks. Есть батник task_remove.cmd. От имени админа
больше никогда это не запускать и не морочить нам голову и себе

**Comment by brushtorr** [comment]
> Помогло решение:
> 
> Закрыть окно с замком и заголовком zapret Удалить службы. Есть батник service_del.cmd. От имени админа Удалить scheduled tasks. Есть батник task_remove.cmd. От имени админа больше никогда это не запускать и не морочить нам голову и себе

Храни тебя господь!!!
